### PR TITLE
Add `gremlins.characters` schema

### PR DESCRIPTION
**Pull request by TheSench**
## Description
I added a JSON schema for the `gremlins.characters` objects.  This was done by adding the schema underneath the `additionalProperties` property, which defines configuration for any arbitrary keys added to this configuration object (i.e. the hexcode key for the given gremlin being configured.  Each entry now consists of the following properties:
* `level` (enum - `error|warning|info` - **required**)
* `description` (string - _optional_)
* `zeroWidth` (boolean - _optional_)
* `hideGutterIcon` (boolean - _optional_)
* `overviewRulerColor`  (boolean - _optional_)

## Motivation and Context
This change makes it easier to configure the `gremlins.characters` setting by providing intellisense for the fields.

## How Has This Been Tested?
Manual testing by mousing over entries in `settings.json`.

## Screenshots (if appropriate):
image
image
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by TheSench** [comment]
I would love some feedback on the descriptions.  For instance, I could see things like `default: false` being added to some of the boolean properties.

**Comment by nhoizey** [comment]
@TheSench that's another awesome addition, thanks a lot!

How would a `default: false` help, if the default value when the property is not set is already `false`? I guess people would add this property to set it to `true` instead.

**Comment by TheSench** [comment]
> @TheSench that's another awesome addition, thanks a lot!
> 
> How would a `default: false` help, if the default value when the property is not set is already `false`? I guess people would add this property to set it to `true` instead.

`default: false` in the schema simply makes the default obvious to the end-user.

**Comment by nhoizey** [comment]
Oh, ok. I thought it would suggest `false` as first value.

That's nice to show what the default value is, then. 👍

**Comment by TheSench** [comment]
> Oh, ok. I thought it would suggest `false` as first value.
> 
> That's nice to show what the default value is, then. 👍

It shows you this in the intellisense in `settings.json`:
image

**Comment by nhoizey** [comment]
@TheSench this is perfect!

**Pull request merged**
