### PR TITLE
Add "paragraph separator" to default characters

### PR DESCRIPTION
**Pull request by loilo**
## Description
Added the [Paragraph Separator (U+2029)](https://www.compart.com/en/unicode/U+2029) to the list of default characters.

## Motivation and Context
This is a hard-to-find zero-width character which can be added through copying paragraph text from graphics editors like Photoshop or Sketch (got it from a PSD converted to a Sketch file, not sure which the original source of the character was).

Generally, one could add all zero-width characters from the Unicode [General Punctuation](https://www.compart.com/en/unicode/block/U+2000) block (i.e. all characters on the linked page which are represented by their abbreviation with a dotted border).

## How Has This Been Tested?
- Added it to my local list of `gremlins.characters`, it correctly reports occurences.
- Added jest test cases

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] ~My change requires a change to the documentation.~
- [ ] ~I have updated the documentation accordingly.~
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
  
  Note that I have updated existing snapshopts (before adding new tests) and cannot verify that the new snapshots are correct. No way for me to interpret them correctly.

- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by nhoizey** [comment]
Sorry @loilo, I missed your PR.

Could you please fix the conflicts, so I can merge it?

**Comment by loilo** [comment]
I have resolved merge conflicts, but reviewing the snapshot diff is kind of hard now to be honest. 🙈

**Comment by nhoizey** [comment]
@loilo I'll check that, thanks!

**Comment by nhoizey** [comment]
All good, merged in next release, thanks! 👍

**Pull request merged**
